spring.application.name=AccMarket
server.servlet.context-path=/api/v1
server.port=${SPRING_PORT}

spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=${EMAIL_HOST}
spring.mail.username=${EMAIL}
spring.mail.password=${EMAIL_CODE_EDU}
spring.mail.port=${EMAIL_PORT}
spring.mail.protocol=smtps



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
